---
- name: Ensure packages is present
  apt: name={{ item }} state=present
  whith_items:
    - default-jdk
    - maven
    - git

- name: Cloning the repo
    git: 
      repo: {{ src_url }}
      dest: {{ work_dir }}
      clone: yes
      update: yes 

- name: Artifact generation
    command: mvn package
    args:
      chdir: {{ work_dir }}
    notify: 
      - moving the artifact st 1