---
- name: Ensure packages is present
  apt: name={{ item }} state=present
  with_items:
    - default-jdk
    - maven
    - git

- name: Cloning the repo
  git: repo={{ src_url }} dest={{ work_dir }} clone=yes update=yes 

- name: Artifact generation
  command: args='mvn package' chdir={{ work_dir }}

- name: moving the artifact st 1
  synchronize: 
    mode: pull 
    src: {{ work_dir }}/target/hello-1.0.war
    dest: /tmp/